### ISSUE TITLE
Save FRR configuration 

### ISSUE THREAD

**Issue by mipxman** [Azure/sonic-frr#19]
Hi Guys! 

I configure vtysh in FRR and save configurtion with write command in SONiC-NOS(https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/). After I reloading system (sudo config reload -y) the bgp container is reloading and my frr configuration was lost! how I can save my configuration like as (/etc/sonic/config_db.json) . 

device : as 7712-32x

```
> sonic# wr
Note: this version of vtysh never writes vtysh.conf
Building Configuration...
Integrated configuration saved to /etc/frr/frr.conf
[OK]
```
`sudo config config save -y `

Regards

**Comment by prsunny** [comment]
FRR configs are generated via templates in Sonic. AFAIK, there is no support to save vtysh config to config_db and restore later. (The saved files via vtysh are ignored). @pavel-shirshov

**Comment by pavel-shirshov** [comment]
There is not such support for now. Sorry.
